name: Trigger auto deployment for ms-challengemeli

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'ChallengeMeLi/**'
    - '.github/workflows/ms-challengemeli-AutoDeployTrigger-668f3fef-2932-43e7-aa7f-191799ecbe1d.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: challengemelicontainer.azurecr.io
          username: ${{ secrets.MSCHALLENGEMELI_REGISTRY_USERNAME }}
          password: ${{ secrets.MSCHALLENGEMELI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: challengemelicontainer.azurecr.io/ms-challengemeli:${{ github.sha }}
          file: ./ChallengeMeLi/Dockerfile
          context: ./ChallengeMeLi/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MSCHALLENGEMELI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ms-challengemeli -g challengeMeLi --server challengemelicontainer.azurecr.io --username  ${{ secrets.MSCHALLENGEMELI_REGISTRY_USERNAME }} --password ${{ secrets.MSCHALLENGEMELI_REGISTRY_PASSWORD }}
            az containerapp update -n ms-challengemeli -g challengeMeLi --image challengemelicontainer.azurecr.io/ms-challengemeli:${{ github.sha }}
